FROM ghcr.io/astral-sh/uv:python3.13-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY ./app ./app
COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

WORKDIR /app

EXPOSE 8000

CMD ["sh", "-c", "uv run python manage.py runserver 0.0.0.0:8000"]